services:
  commander:
    build:
      context: ./commander
      args:
        VITE_API_URL: http://localhost:8081
    container_name: commander
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8081
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: