// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: auth.sql

package sqlite

import (
	"context"
	"time"

	"api/internal/auth"
)

const deleteAllTokens = `-- name: DeleteAllTokens :exec
DELETE FROM auth_tokens
`

func (q *Queries) DeleteAllTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllTokens)
	return err
}

const deleteAuthPassword = `-- name: DeleteAuthPassword :exec
DELETE FROM auth_password WHERE id = 1
`

func (q *Queries) DeleteAuthPassword(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAuthPassword)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM auth_tokens WHERE token_hash = ?1
`

func (q *Queries) DeleteToken(ctx context.Context, tokenHash auth.TokenHash) error {
	_, err := q.db.ExecContext(ctx, deleteToken, tokenHash)
	return err
}

const getAuthPassword = `-- name: GetAuthPassword :one
SELECT hash, updated_at FROM auth_password WHERE id = 1
`

type GetAuthPasswordRow struct {
	Hash      string
	UpdatedAt time.Time
}

func (q *Queries) GetAuthPassword(ctx context.Context) (GetAuthPasswordRow, error) {
	row := q.db.QueryRowContext(ctx, getAuthPassword)
	var i GetAuthPasswordRow
	err := row.Scan(&i.Hash, &i.UpdatedAt)
	return i, err
}

const getValidToken = `-- name: GetValidToken :one
SELECT token_hash, created_at, last_used, expires_at, client_ip
FROM auth_tokens
WHERE token_hash = ?1
  AND expires_at > ?2
`

type GetValidTokenParams struct {
	TokenHash auth.TokenHash
	Now       time.Time
}

func (q *Queries) GetValidToken(ctx context.Context, arg GetValidTokenParams) (AuthToken, error) {
	row := q.db.QueryRowContext(ctx, getValidToken, arg.TokenHash, arg.Now)
	var i AuthToken
	err := row.Scan(
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsed,
		&i.ExpiresAt,
		&i.ClientIp,
	)
	return i, err
}

const insertToken = `-- name: InsertToken :exec
INSERT INTO auth_tokens (token_hash, created_at, last_used, expires_at, client_ip)
VALUES (?1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,
        ?2, ?3)
`

type InsertTokenParams struct {
	TokenHash auth.TokenHash
	ExpiresAt time.Time
	ClientIp  string
}

func (q *Queries) InsertToken(ctx context.Context, arg InsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertToken, arg.TokenHash, arg.ExpiresAt, arg.ClientIp)
	return err
}

const runTokenPrune = `-- name: RunTokenPrune :execrows
DELETE FROM auth_tokens WHERE expires_at <= ?1
`

func (q *Queries) RunTokenPrune(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, runTokenPrune, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const touchToken = `-- name: TouchToken :exec
UPDATE auth_tokens
SET last_used = CURRENT_TIMESTAMP,
    expires_at = ?1,
    client_ip = ?2
WHERE token_hash = ?3
`

type TouchTokenParams struct {
	ExpiresAt time.Time
	ClientIp  string
	TokenHash auth.TokenHash
}

func (q *Queries) TouchToken(ctx context.Context, arg TouchTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchToken, arg.ExpiresAt, arg.ClientIp, arg.TokenHash)
	return err
}

const upsertAuthPassword = `-- name: UpsertAuthPassword :exec
INSERT INTO auth_password (id, hash, updated_at)
VALUES (1, ?1, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE
    SET hash = excluded.hash,
        updated_at = excluded.updated_at
`

func (q *Queries) UpsertAuthPassword(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, upsertAuthPassword, hash)
	return err
}
