// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: history.sql

package sqlite

import (
	"context"

	"api/internal/session"
)

const pruneHistoryOlderThan = `-- name: PruneHistoryOlderThan :execrows
DELETE FROM history_points
WHERE session_id = ?1
  AND data_type = ?2
  AND game_time_id < CAST(?3 AS INTEGER)
`

type PruneHistoryOlderThanParams struct {
	SessionID session.ID
	DataType  string
	Cutoff    int64
}

func (q *Queries) PruneHistoryOlderThan(ctx context.Context, arg PruneHistoryOlderThanParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHistoryOlderThan, arg.SessionID, arg.DataType, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const queryHistoryBucketed = `-- name: QueryHistoryBucketed :many
WITH bucketed AS (
    SELECT game_time_id, data,
           game_time_id / CAST(?1 AS INTEGER) AS bucket
    FROM history_points
    WHERE session_id = ?2
      AND data_type = ?3
      AND game_time_id > CAST(?4 AS INTEGER)
      AND game_time_id <= CAST(?5 AS INTEGER)
),
newest AS (
    SELECT b.game_time_id, b.data
    FROM bucketed b
    WHERE b.game_time_id = (
        SELECT MAX(b2.game_time_id) FROM bucketed b2 WHERE b2.bucket = b.bucket
    )
    ORDER BY b.game_time_id DESC
    LIMIT IIF(CAST(?6 AS INTEGER) > 0, CAST(?6 AS INTEGER), -1)
)
SELECT game_time_id, data FROM newest ORDER BY game_time_id ASC
`

type QueryHistoryBucketedParams struct {
	BucketSeconds int64
	SessionID     session.ID
	DataType      string
	Since         int64
	ToID          int64
	Lim           int64
}

type QueryHistoryBucketedRow struct {
	GameTimeID int64
	Data       string
}

func (q *Queries) QueryHistoryBucketed(ctx context.Context, arg QueryHistoryBucketedParams) ([]QueryHistoryBucketedRow, error) {
	rows, err := q.db.QueryContext(ctx, queryHistoryBucketed,
		arg.BucketSeconds,
		arg.SessionID,
		arg.DataType,
		arg.Since,
		arg.ToID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryHistoryBucketedRow
	for rows.Next() {
		var i QueryHistoryBucketedRow
		if err := rows.Scan(&i.GameTimeID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const queryHistoryRaw = `-- name: QueryHistoryRaw :many
SELECT game_time_id, data
FROM (
    SELECT game_time_id, data
    FROM history_points
    WHERE session_id = ?1
      AND data_type = ?2
      AND game_time_id > CAST(?3 AS INTEGER)
      AND game_time_id <= CAST(?4 AS INTEGER)
    ORDER BY game_time_id DESC
    LIMIT IIF(CAST(?5 AS INTEGER) > 0, CAST(?5 AS INTEGER), -1)
) AS newest
ORDER BY game_time_id ASC
`

type QueryHistoryRawParams struct {
	SessionID session.ID
	DataType  string
	Since     int64
	ToID      int64
	Lim       int64
}

type QueryHistoryRawRow struct {
	GameTimeID int64
	Data       string
}

func (q *Queries) QueryHistoryRaw(ctx context.Context, arg QueryHistoryRawParams) ([]QueryHistoryRawRow, error) {
	rows, err := q.db.QueryContext(ctx, queryHistoryRaw,
		arg.SessionID,
		arg.DataType,
		arg.Since,
		arg.ToID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QueryHistoryRawRow
	for rows.Next() {
		var i QueryHistoryRawRow
		if err := rows.Scan(&i.GameTimeID, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertHistoryPoint = `-- name: UpsertHistoryPoint :exec
INSERT INTO history_points (session_id, data_type, game_time_id, data)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
ON CONFLICT(session_id, data_type, game_time_id)
DO UPDATE SET data = excluded.data
`

type UpsertHistoryPointParams struct {
	SessionID  session.ID
	DataType   string
	GameTimeID int64
	Data       string
}

func (q *Queries) UpsertHistoryPoint(ctx context.Context, arg UpsertHistoryPointParams) error {
	_, err := q.db.ExecContext(ctx, upsertHistoryPoint,
		arg.SessionID,
		arg.DataType,
		arg.GameTimeID,
		arg.Data,
	)
	return err
}
