// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: instance.sql

package sqlite

import (
	"context"
	"time"
)

const completeInstanceSetup = `-- name: CompleteInstanceSetup :execrows
UPDATE instance
SET initialized_at       = CURRENT_TIMESTAMP,
    auth_mode            = ?1,
    bootstrap_token_hash = NULL
WHERE id = 1
  AND initialized_at IS NULL
`

func (q *Queries) CompleteInstanceSetup(ctx context.Context, authMode string) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeInstanceSetup, authMode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const ensureInstance = `-- name: EnsureInstance :exec
INSERT INTO instance (id) VALUES (1)
ON CONFLICT(id) DO NOTHING
`

func (q *Queries) EnsureInstance(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureInstance)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT initialized_at, auth_mode, bootstrap_token_hash, created_at
FROM instance WHERE id = 1
`

type GetInstanceRow struct {
	InitializedAt      *time.Time
	AuthMode           string
	BootstrapTokenHash *string
	CreatedAt          time.Time
}

func (q *Queries) GetInstance(ctx context.Context) (GetInstanceRow, error) {
	row := q.db.QueryRowContext(ctx, getInstance)
	var i GetInstanceRow
	err := row.Scan(
		&i.InitializedAt,
		&i.AuthMode,
		&i.BootstrapTokenHash,
		&i.CreatedAt,
	)
	return i, err
}

const setAuthMode = `-- name: SetAuthMode :exec
UPDATE instance
SET auth_mode = ?1
WHERE id = 1
`

func (q *Queries) SetAuthMode(ctx context.Context, authMode string) error {
	_, err := q.db.ExecContext(ctx, setAuthMode, authMode)
	return err
}

const setBootstrapTokenHash = `-- name: SetBootstrapTokenHash :exec
UPDATE instance
SET bootstrap_token_hash = ?1
WHERE id = 1
`

func (q *Queries) SetBootstrapTokenHash(ctx context.Context, bootstrapTokenHash *string) error {
	_, err := q.db.ExecContext(ctx, setBootstrapTokenHash, bootstrapTokenHash)
	return err
}
