// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"time"

	"api/internal/auth"
	"api/internal/session"
)

type AuthPassword struct {
	ID        int64
	Hash      string
	IsDefault int64
	UpdatedAt time.Time
}

type AuthToken struct {
	Token     auth.Token
	CreatedAt time.Time
	LastUsed  time.Time
	ExpiresAt time.Time
	ClientIp  string
}

type HistoryPoint struct {
	SessionID  session.ID
	SaveName   string
	DataType   string
	GameTimeID int64
	Data       string
}

type Session struct {
	ID          session.ID
	Name        string
	Address     string
	SessionName string
	IsPaused    int64
	CreatedAt   time.Time
}

type Setting struct {
	Key   string
	Value string
}
