// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package sqlite

import (
	"context"
	"time"

	"api/internal/auth"
	"api/internal/session"
)

type Querier interface {
	CompleteInstanceSetup(ctx context.Context, authMode string) (int64, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	DeleteAllTokens(ctx context.Context) error
	DeleteAuthPassword(ctx context.Context) error
	DeleteSession(ctx context.Context, id session.ID) error
	DeleteToken(ctx context.Context, tokenHash auth.TokenHash) error
	EnsureInstance(ctx context.Context) error
	GetAuthPassword(ctx context.Context) (GetAuthPasswordRow, error)
	GetInstance(ctx context.Context) (GetInstanceRow, error)
	GetSession(ctx context.Context, id session.ID) (Session, error)
	GetSetting(ctx context.Context, key string) (Setting, error)
	GetValidToken(ctx context.Context, arg GetValidTokenParams) (AuthToken, error)
	InsertToken(ctx context.Context, arg InsertTokenParams) error
	ListSessions(ctx context.Context) ([]Session, error)
	ListSettings(ctx context.Context) ([]Setting, error)
	PruneHistoryOlderThan(ctx context.Context, arg PruneHistoryOlderThanParams) (int64, error)
	QueryHistoryBucketed(ctx context.Context, arg QueryHistoryBucketedParams) ([]QueryHistoryBucketedRow, error)
	QueryHistoryRaw(ctx context.Context, arg QueryHistoryRawParams) ([]QueryHistoryRawRow, error)
	RunTokenPrune(ctx context.Context, now time.Time) (int64, error)
	SetAuthMode(ctx context.Context, authMode string) error
	SetBootstrapTokenHash(ctx context.Context, bootstrapTokenHash *string) error
	TouchToken(ctx context.Context, arg TouchTokenParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpsertAuthPassword(ctx context.Context, hash string) error
	UpsertHistoryPoint(ctx context.Context, arg UpsertHistoryPointParams) error
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
