// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: sessions.sql

package sqlite

import (
	"context"

	"api/internal/session"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, name, address, save_name, created_at)
VALUES (?1, ?2, ?3, ?4, CURRENT_TIMESTAMP)
`

type CreateSessionParams struct {
	ID       session.ID
	Name     string
	Address  string
	SaveName string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.SaveName,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?1
`

func (q *Queries) DeleteSession(ctx context.Context, id session.ID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, name, address, save_name, is_paused, created_at
FROM sessions WHERE id = ?1
`

func (q *Queries) GetSession(ctx context.Context, id session.ID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.SaveName,
		&i.IsPaused,
		&i.CreatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, name, address, save_name, is_paused, created_at
FROM sessions ORDER BY created_at ASC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.SaveName,
			&i.IsPaused,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET name = ?1,
    address = ?2,
    is_paused = ?3
WHERE id = ?4
`

type UpdateSessionParams struct {
	Name     string
	Address  string
	IsPaused int64
	ID       session.ID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.Name,
		arg.Address,
		arg.IsPaused,
		arg.ID,
	)
	return err
}
